 name: CI/CD Workflow

 on:
   pull_request:
     branches:
       - main
   push:
     branches:
       - main
 jobs:
   build:
     runs-on: ubuntu-latest

     strategy:
       matrix:
         node-version: [16.x]

     steps:
       - uses: actions/checkout@v2

       - name: Set up Node.js ${{ matrix.node-version }}
         uses: actions/setup-node@v2
         with:
           node-version: ${{ matrix.node-version }}

       # Github Repository Secrets를 통해 환경 변수 파일을 생성합니다.
       - name: Generate Environment Variables File for Production
         run: |
           echo "SETENV" >> ./frontend/.env
       - name: Install dependencies for frontend
         working-directory: ./frontend
         run: yarn add
         
       - name: Run frontend
         working-directory: ./frontend
         run: yarn dev & sleep 5; pkill -f "node ."
