 name: CI/CD Workflow

 on:
   pull_request:
     branches:
       - main
   push:
     branches:
       - main
 jobs:
   build:
     runs-on: ubuntu-latest

     strategy:
       matrix:
         node-version: [16.x]

     steps:
       - uses: actions/checkout@v2

       - name: Set up Node.js ${{ matrix.node-version }}
         uses: actions/setup-node@v2
         with:
           node-version: ${{ matrix.node-version }}
       - name: Install dependencies for frontend
         working-directory: ./frontend
         run: yarn install

       # Github Repository Secrets를 통해 환경 변수 파일을 생성합니다.
       - name: Generate Environment Variables File for .env
         run: |
           echo "SETENV" >> ./frontend/.env

       - name: Run frontend
         working-directory: ./frontend
         run: yarn dev & sleep 5; pkill -f "node ."

#        - name: Generate Environment Variables File for adam.json
#          run: |
#            echo "ADAMJSON" >> ./backend/config/adam.json

#        - name: Generate Environment Variables File for ormconfig.dev.json
#          run: |
#            echo "ORMCONFIGDEVJSON" >> ./backend/config/ormconfig.dev.json

#        - name: Install dependencies for backend
#          working-directory: ./backend
#          run: yarn install

#        - name: Run backend
#          working-directory: ./backend
#          run: yarn dev & sleep 5; pkill -f "node ."
